# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Improving software by focusing on better feedback
email: andersen.theo@gmail.com
description: djfk dlfj sldkfj dslkfj sdl

baseurl: "" 
url: "http://www.nettreo.com" 
twitter_username: TheoAndersen
github_username:  TheoAndersen

# Build settings
markdown: kramdown








