# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Improving software by focusing on better feedback
email: andersen.theo@gmail.com
description: Blog that focuses on software development feedback and all related to this.

baseurl: "" 
url: "http://www.nettreo.com" 
twitter_username: TheoAndersen
github_username:  TheoAndersen

image: /assets/blog_udsnit.png

# Build settings
markdown: kramdown

gems: [jekyll-seo-tag, jekyll-sitemap, jekyll-auto-image]








